#' Log coefficent conversion table helper function
#'
#' @import dplyr
#'
#' @param gender_val Name of the gender coef variable
#' @param race_eth_val Name of the race_eth coef variable
#' @param coef_df The coef data frame generated from the model
#' @return Table of pay gap and adjusted pay gap based on model coefficients

log_to_prop <- function(gender_val, race_eth_val, coef_df){
  row_names <- rownames(coef_df)
  gender_exists <- class(try(gender_val, silent = TRUE)) != "try-error"
  race_eth_exists <- class(try(race_eth_val, silent = TRUE)) != "try-error"

  if(gender_exists & race_eth_exists){
    ifelse(gender_val == "Male",
           multiplier1 <-  1,
           {
             coef_of_interest <- coef_df[which(row_names == paste0("gender",gender_val)),"Estimate"]
             multiplier1 <- exp(coef_of_interest)
           })
    ifelse(race_eth_val == "NH White",
           multiplier2 <- 1,
           {
             coef_of_interest <- coef_df[which(row_names == paste0("race_eth",race_eth_val)),"Estimate"]
             multiplier2 <- exp(coef_of_interest)
           })
    ifelse(gender_val == "Male" | race_eth_val == "NH White",
           multiplier3 <- 1,
           {
             coef_of_interest <- coef_df[which(row_names == paste0("gender",gender_val,":","race_eth",race_eth_val)),"Estimate"]
             multiplier3 <- exp(coef_of_interest)
           })
    return(multiplier1 * multiplier2 * multiplier3)
  } else{
    if(gender_exists){
      ifelse(gender_val == "Male",
             multiplier <-  1,
             {
               coef_of_interest <- coef_df[which(row_names == paste0("gender",gender_val)),"Estimate"]
               multiplier <- exp(coef_of_interest)
             })
    }

    if(race_eth_exists){
      ifelse(race_eth_val == "NH White",
             multiplier <-  1,
             {
               coef_of_interest <- coef_df[which(row_names == paste0("race_eth",race_eth_val)),"Estimate"]
               multiplier <- exp(coef_of_interest)
             })
    }
    return(multiplier)
  }
}

#' Base Hierarchical and Interaction Model
#'
#' This function will create either a \code{basic_model} or \code{interaction_model} in your global environment. Additionally, it will create a paygap table based on the coefficients
#' TASKS that use this:
#' Gender (unadjusted too)
#' Race/Ethnicity (unadjusted too)
#' Gender & Race/Ethnicity (unadjusted too)
#'
#' NOTE: This function will ONLY work if the data input is generated by \code{payeqfunctions::clean_data()} due to the naming scheme.
#'
#' @import dplyr
#' @import lme4
#'
#' @param data Pass the cleaned dataset using \code{payeqfunctions::clean_data()} to this
#' @param interaction_model Default is FALSE. When TRUE, it'll run the interaction model
#' @return List of pay gap tables. When running the non-interaction model, the first item on the list is the gender pay table and second item is race_eth pay table
#' @export
#' @examples
#' \dontrun{
#' # Regular lme model
#' pay_gap_table(data = cleaned_dataset)
#' # output[[1]] for gender pay gap table
#' # output[[2]] for race_eth pay gap table
#'
#' # Interaction lme model
#' pay_gap_table(data = cleaned_dataset, interaction = TRUE)
#' }

pay_gap_table <- function(data, interaction_model = FALSE){
  pay_gap <- list()
  if(interaction_model){
    model <- lmer(data = data, log(base_salary) ~ gender * race_eth + age_above18 + I(age_above18^2) +
                    years_from_start + I(years_from_start^2) + managerial +
                    (1 | agency) +
                    (1 | civil_service_title_code) +
                    (1 | civil_service_title_code:career_level_title_level) +
                    (1 | civil_service_title_code:career_level_title_suffix))

    pay_gap[[1]] <- data %>%
      filter(gender != "Unknown or Choose not to Disclose") %>%
      group_by(gender,race_eth) %>%
      summarise(mean = mean(base_salary),
                med = median(base_salary),
                num_workers = n()) %>%
      ungroup %>%
      mutate(cents = med/subset(.,race_eth == "NH White" & gender == "Male")$med)

    assign("interaction_model",model, .GlobalEnv)
  } else{
    model <- lmer(data = data, log(base_salary) ~ gender + race_eth + age_above18 + I(age_above18^2) +
                    years_from_start + I(years_from_start^2) + managerial +
                    (1 | agency) +
                    (1 | civil_service_title_code) +
                    (1 | civil_service_title_code:career_level_title_level) +
                    (1 | civil_service_title_code:career_level_title_suffix))

    pay_gap[[1]] <- data %>%
      filter(gender != "Unknown or Choose not to Disclose") %>%
      group_by(gender) %>%
      summarise(mean = mean(base_salary),
                med = median(base_salary),
                num_workers = n()) %>%
      ungroup %>%
      mutate(cents = med/subset(.,gender == "Male")$med)

    pay_gap[[2]] <- data %>%
      group_by(race_eth) %>%
      summarise(mean = mean(base_salary),
                med = median(base_salary),
                num_workers = n()) %>%
      ungroup %>%
      mutate(cents = med/subset(.,race_eth == "NH White")$med)

    assign("basic_model",model, .GlobalEnv)
  }

  model_coef <- as.data.frame(summary(model)$coefficients)

  output <- lapply(pay_gap,function(x) {
    x %>%
      rowwise %>%
      mutate(adj_cents = log_to_prop(gender_val = gender,
                                     race_eth_val = race_eth,
                                     coef_df = model_coef))
    })

  return(output)
}
